version: "3"
services:
  odoo12:
   image: odoo:16.0
   ports:
     - "8078:8069"
   environment:
     DB_ENV_POSTGRES_PASSWORD: odo124vY#*9843F
     DB_ENV_POSTGRES_USER: odoo
   volumes:
    - /docker16/addons:/mnt/extra-addons
    - /docker16/data:/var/lib/odoo/data
    - /docker16/logs:/var/lib/odoo/logs
    - /docker16/addons-extra:/mnt/extra-addons-customize

  

   links:
    - "db2:db"

  db2:
   image: postgres:12
   environment:
     POSTGRES_USER: odoo
     POSTGRES_PASSWORD: odo124vY#*9843F
     POSTGRES_DB: postgres

   volumes:
    - /docker16/db2:/var/lib/postgresql/data
